version: "3.7"
services:
  stream:
    build: streamcollector/Dockerfile
    image: stream
    user: ec2-user
    ports:
       - 80:80
  visualization:
    build: visualization/Dockerfile
    user: ec2-user
    image: visualization
    ports:
       - 8080:8080
